export const chatsData = [
  {
    id: 1,
    title: 'We & Me',
    time: '1 minutes a go',
    image: require('../assets/chats/we-me-chat.png'),
    newMessages: 1,
    messages: [],
  },
  {
    id: 2,
    title: 'Brothers',
    time: '6 year a go',
    image: require('../assets/chats/brothers.png'),
    newMessages: 4,
    messages: [],
  },
  {
    id: 3,
    title: 'Sisters',
    time: '7 minutes a go',
    image: require('../assets/chats/sisters.jpeg'),
    newMessages: 13,
    messages: [],
  },
  {
    id: 4,
    title: 'Brainstorm',
    time: '2 hours a go',
    image: require('../assets/chats/brainstorm.png'),
    newMessages: 44,
    messages: [],
  },
  {
    id: 5,
    title: 'Neighbors',
    time: '8 days a go',
    image: require('../assets/chats/neibours.jpeg'),
    newMessages: 3,
    messages: [],
  },
  {
    id: 6,
    title: 'Zone',
    time: '9 minutes a go',
    image: require('../assets/chats/zone.jpeg'),
    newMessages: 2,
    messages: [],
  },
];
